name: EasyUHC
version: 11.2.1
main: com.stefancooper.EasyUHC.Plugin
description: A Plugin for running UHCs on Paper servers
api-version: 26.1.2
bootstrapper: com.stefancooper.EasyUHC.Bootstrap
permissions:
  easyuhc.command:
    default: op