name: EasyUHC
version: 11.2.2
author: Stefan Cooper
main: com.stefancooper.EasyUHC.Plugin
api-version: 26.1.2
website: https://stefancooper.com
permissions:
  easyuhc.command:
    default: op
